# Generated by Django 5.0.3 on 2024-08-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_routine_routineday_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='type',
            field=models.CharField(choices=[('Course', 'Course'), ('Activity', 'Activity')], max_length=8),
        ),
        migrations.AlterField(
            model_name='routineday',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schedule.routine'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Reminder', 'Reminder'), ('Assignment', 'Assignment'), ('Exam', 'Exam')], max_length=10),
        ),
    ]
